update pt-br norme to v4
42School/norminette pull request #430
Opened 2023-09-02 15:25 UTC by vitorsantanna2

I did an update from PT_BR Norme version 3 to PT_BR Norme version 4

2023-09-02 16:51 UTC, NiumXp requested changes

2023-09-02 16:51 UTC, NiumXp commented on pdf/pt_br.norm.tex
> +            \item Usando variáveis globais que não são marcadas como constante e estática é proibido e é considerado um erro de norma, há menos que seja explicitamente permitido no projeto.
```suggestion
            \item Usar variáveis globais é proibido e considerado um erro de norma, há menos que seja explicitamente permitido o uso no projeto.
```

2023-09-02 16:51 UTC, NiumXp commented on pdf/pt_br.norm.tex
> +		Uma declaração ou função mal feita normalmente vem com nomes não explícitos como f1, f2... para as funções e a, b, i, ... para as declarações.
```suggestion
		Uma declaração ou função mal feita normalmente vem com nomes não inteligíveis como f1, f2, etc. para as funções e, a, b, i, etc. para declarações.
```

2023-09-02 16:51 UTC, NiumXp commented on pdf/pt_br.norm.tex
> +            \item Um comentário não pode ser usado para justificar declarações ou  uma função
```suggestion
            \item Um comentário não pode ser usado para justificar declarações ou uma função 
```

2023-09-02 16:51 UTC, NiumXp commented on pdf/pt_br.norm.tex
> +		Uma função que tem o único objetivo de evitar a norma, sem um único propósito lógico, também é considerado uma função mal feita.
```suggestion
		Uma função cujo objetivo é evitar ou burlar a norma, sem um único propósito lógico, também é considerado uma função mal feita.
```

2023-09-02 16:51 UTC, NiumXp commented on pdf/pt_br.norm.tex
> +		Por favor lembre se que é desejável ter funções limpas e legíveis que realizem uma clara e simples tarefa cada. Evite qualquer técnica de ofuscação do código como \emph{one-liner}..
```suggestion
		Por favor, lembre-se de que é desejável ter funções limpas e legíveis que realizem uma clara e simples tarefa. Evite qualquer técnica de ofuscação de código como \emph{one-liner}.
```

2023-09-02 16:51 UTC, NiumXp commented on pdf/pt_br.norm.tex
> +	\item Instruções de pré-processamento são proibidas fora do escopo global.
```suggestion
            \item Instruções de pré-processamento são proibidas fora do escopo global.
```

2023-09-02 16:51 UTC, NiumXp commented on pdf/pt_br.norm.tex
> +          mais recente. Cada vez que o arquivo é salvo em disco, a informação deve ser atualizada automaticamente.
```suggestion
          mais recente. Cada vez que o arquivo for salvo em disco, a informação deve ser atualizada automaticamente.
```

2023-09-02 16:51 UTC, NiumXp commented on pdf/pt_br.norm.tex
> +	\item Funções seguidas de chaves, declaradores ou estruturas de controle devem ser precedidas e seguidas de uma nova linha.
```suggestion
                \item Funções seguidas de chaves, declaradores ou estruturas de controle devem ser precedidas e seguidas de uma nova linha.
```

2023-09-02 17:03 UTC, vitorsantanna2 commented
Accepted Suggestions

2023-09-05 07:50 UTC, matthieu42Network approved these changes

2023-09-05 07:50 UTC, merged