Add a new user/beginner friendly errors system
42School/norminette pull request #505
Opened 2024-07-01 00:52 UTC by NiumXp

Hi, this is one of my drafts (maybe 7 months ago) focused on beginners (and quality of life) that I wrote for norminette when @matthieu42Network was accepting my PRs, I'm not sure if he's still available, but recently it seems like new people became collaborators, this made me happy and willing to continue with contributions.

## New errors formatting
To use the new format is not necessary a new configuration, just run your norminette:
```
(.venv) niumxp@DESKTOP-LRN507C:~/oss/norminette$ cat -A test.c
#define exit 42$
$
int^IMain(void) {$
^Ireturn exit;$
}$
(.venv) niumxp@DESKTOP-LRN507C:~/oss/norminette$ norminette test.c
test.c:1:1 INVALID_HEADER Missing or invalid 42 header
test.c:1:9 MACRO_NAME_CAPITAL
     1 | #define exit 42
       |         ^^^^ Macro name must be capitalized
test.c:3:5 FORBIDDEN_CHAR_NAME
     3 | int Main(void) {
       |     ^^^^ user defined identifiers should contain only lowercase characters, digits or '_'
test.c:3:16 BRACE_NEWLINE
     3 | int Main(void) {
       |                ^ Expected newline before brace
test.c:4:12 RETURN_PARENTHESIS
     4 |     return exit;
       |            ^^^^ Return value must be in parenthesis
```
I added a red color to the errors:
![image](https://github.com/42School/norminette/assets/43611165/28cfcf53-6b82-4023-8bb9-f60e600243cb)

2024-09-11 21:55 UTC, xtrm-en commented
Subjective nit, this should probably have a bit more padding for readability's sake. Other than that, looks pretty amazing :)

2025-02-04 17:50 UTC, otto-mata requested changes
Overall a very good new feature, the norminette would really benefit from its addition!
Some changes are still necessary in my opinion, but please you are absolutely free to discuss your choices!

Bests,
tblochet

2025-02-04 17:50 UTC, otto-mata commented on norminette/errors.py
> +class ShortErrorsFormatter(_formatter):
It might be a better idea to create another `_formatter` class, rather than modifying the existing default class.
maybe `class CompilerLikeErrorsFormatter`

2025-02-04 17:50 UTC, otto-mata commented on norminette/file.py
> +            #     return self._line_to_index[lineno + column]
Unnecessary comments

2025-02-04 17:50 UTC, otto-mata commented on tests/rules/samples/test_comments.out
See last comment, potentially breaking change

2025-02-04 17:50 UTC, otto-mata commented on tests/rules/samples/check_preprocessor_indent.out
> +Error: SPC_BEFORE_NL        (line:  26, col:   2):	Space before newline
This is a potentially breaking change, it should be in a separate PR

2025-02-04 17:50 UTC, otto-mata commented on norminette/rules/check_expression_statement.py
> +                    context.errors.add(error)
It might be better to do a complete refacto on this,
There are about 145 more `context.new_error()` still being used.
Maybe in another PR ?

2025-02-04 17:50 UTC, otto-mata commented on tests/test_errors.py
> +# from norminette.errors import HumanizedErrorsFormatter
Unnecessary comment

2025-03-31 11:57 UTC, NiumXp commented on norminette/errors.py
> +class ShortErrorsFormatter(_formatter):
Hello! When I designed these classes, I already intended to replace them, since they don't affect the tests (because I made it so they wouldn't :D) and also the new style/formatting would already be used.

2025-03-31 12:01 UTC, NiumXp commented on tests/rules/samples/check_preprocessor_indent.out
> +Error: SPC_BEFORE_NL        (line:  26, col:   2):	Space before newline
You're right about a separate PR, it fixes the checking of trailing spaces, which is off-topic for this PR, but when I was developing this feature, I was considering not creating a new PR since it was something simple. And it's not a breaking change, it's a fix, a good one!

2025-03-31 12:05 UTC, NiumXp commented on norminette/rules/check_expression_statement.py
> +                    context.errors.add(error)
Hello! When (if) this PR is accepted, we can add an overload to avoid this boiler plate, but my idea at the time was not to do this because it would add a much richer system when analyzing the code, today there is no parsing analysis and I would add it (solving countless bugs and opening doors for analysis even at runtime).

2025-06-06 12:40 UTC, Asandolo requested changes
Hello can you tell us if this PR is still relevant, if is it can you rebase and resolve all conflict ? 

Have a nice day

2025-06-06 13:16 UTC, NiumXp commented
Hello, @Asandolo!

Thanks for checking in. Yep, this PR is still relevant! I’ll take care of the rebase and sort out the conflicts shortly.

Really appreciate you reaching out. Hope your day’s going well!

2026-06-01 02:19 UTC, closed without merging